version: '3.8'
services:
  mysql8:
    image: mysql:8.0.27
    container_name: "${COMPOSE_PROJECT_NAME}_mysql8"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    env_file:
      - ./env/mysql.env
    volumes:
      - mysql8:/var/lib/mysql

  account-http:
    build:
      context: .
    container_name: "${COMPOSE_PROJECT_NAME}_account-http"
    command: ./run_server.sh
    ports:
      - '3001:3001'
    env_file:
      - ./env/account-http.env
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
    depends_on:
      - mysql8

volumes:
  mysql8:
  bundle:
  node_modules:
  packs:
  rails_cache:
